spring:
  application:
    name: order-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/order_db
    username: root
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true

server:
  port: 8081

grpc:
  client:
    user-service:
      address: static://127.0.0.1:9090
      negotiation-type: plaintext

logging:
  level:
    root: info
    com.example.order: debug
    org.hibernate.SQL: debug
